
export default function Home() {
  return (
    <div>
      <h1>Home page</h1>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste ipsa tempore consequuntur quibusdam voluptatum nam! Dolor itaque dicta voluptates. Ratione est ipsa earum consequuntur nobis voluptatibus ipsam velit pariatur aut fuga, beatae reprehenderit itaque aperiam! Ipsam ipsa asperiores repellat dolor molestias? Et unde provident quos delectus vel, eos mollitia laboriosam necessitatibus dolor. Ea sit animi ullam, reprehenderit dignissimos veniam hic rem quaerat, quibusdam cupiditate incidunt nesciunt explicabo eos officiis velit accusantium commodi totam voluptatem dolorem cumque provident expedita. Natus cupiditate dignissimos, commodi, quidem facilis quod nulla vero quia similique sit quae. Praesentium culpa nisi dolorem, eaque asperiores magnam minima quibusdam consectetur perspiciatis temporibus fugiat soluta vero exercitationem necessitatibus atque nemo placeat laudantium. Quidem modi, nesciunt accusamus natus nihil, ipsum reiciendis id nisi eos quas, aperiam rerum inventore excepturi pariatur! Fugiat, cum vitae voluptates voluptatem, ullam atque velit consequatur aliquam iure quia similique soluta ipsum numquam minus autem dolores ut consequuntur!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste ipsa tempore consequuntur quibusdam voluptatum nam! Dolor itaque dicta voluptates. Ratione est ipsa earum consequuntur nobis voluptatibus ipsam velit pariatur aut fuga, beatae reprehenderit itaque aperiam! Ipsam ipsa asperiores repellat dolor molestias? Et unde provident quos delectus vel, eos mollitia laboriosam necessitatibus dolor. Ea sit animi ullam, reprehenderit dignissimos veniam hic rem quaerat, quibusdam cupiditate incidunt nesciunt explicabo eos officiis velit accusantium commodi totam voluptatem dolorem cumque provident expedita. Natus cupiditate dignissimos, commodi, quidem facilis quod nulla vero quia similique sit quae. Praesentium culpa nisi dolorem, eaque asperiores magnam minima quibusdam consectetur perspiciatis temporibus fugiat soluta vero exercitationem necessitatibus atque nemo placeat laudantium. Quidem modi, nesciunt accusamus natus nihil, ipsum reiciendis id nisi eos quas, aperiam rerum inventore excepturi pariatur! Fugiat, cum vitae voluptates voluptatem, ullam atque velit consequatur aliquam iure quia similique soluta ipsum numquam minus autem dolores ut consequuntur!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste ipsa tempore consequuntur quibusdam voluptatum nam! Dolor itaque dicta voluptates. Ratione est ipsa earum consequuntur nobis voluptatibus ipsam velit pariatur aut fuga, beatae reprehenderit itaque aperiam! Ipsam ipsa asperiores repellat dolor molestias? Et unde provident quos delectus vel, eos mollitia laboriosam necessitatibus dolor. Ea sit animi ullam, reprehenderit dignissimos veniam hic rem quaerat, quibusdam cupiditate incidunt nesciunt explicabo eos officiis velit accusantium commodi totam voluptatem dolorem cumque provident expedita. Natus cupiditate dignissimos, commodi, quidem facilis quod nulla vero quia similique sit quae. Praesentium culpa nisi dolorem, eaque asperiores magnam minima quibusdam consectetur perspiciatis temporibus fugiat soluta vero exercitationem necessitatibus atque nemo placeat laudantium. Quidem modi, nesciunt accusamus natus nihil, ipsum reiciendis id nisi eos quas, aperiam rerum inventore excepturi pariatur! Fugiat, cum vitae voluptates voluptatem, ullam atque velit consequatur aliquam iure quia similique soluta ipsum numquam minus autem dolores ut consequuntur!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste ipsa tempore consequuntur quibusdam voluptatum nam! Dolor itaque dicta voluptates. Ratione est ipsa earum consequuntur nobis voluptatibus ipsam velit pariatur aut fuga, beatae reprehenderit itaque aperiam! Ipsam ipsa asperiores repellat dolor molestias? Et unde provident quos delectus vel, eos mollitia laboriosam necessitatibus dolor. Ea sit animi ullam, reprehenderit dignissimos veniam hic rem quaerat, quibusdam cupiditate incidunt nesciunt explicabo eos officiis velit accusantium commodi totam voluptatem dolorem cumque provident expedita. Natus cupiditate dignissimos, commodi, quidem facilis quod nulla vero quia similique sit quae. Praesentium culpa nisi dolorem, eaque asperiores magnam minima quibusdam consectetur perspiciatis temporibus fugiat soluta vero exercitationem necessitatibus atque nemo placeat laudantium. Quidem modi, nesciunt accusamus natus nihil, ipsum reiciendis id nisi eos quas, aperiam rerum inventore excepturi pariatur! Fugiat, cum vitae voluptates voluptatem, ullam atque velit consequatur aliquam iure quia similique soluta ipsum numquam minus autem dolores ut consequuntur!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste ipsa tempore consequuntur quibusdam voluptatum nam! Dolor itaque dicta voluptates. Ratione est ipsa earum consequuntur nobis voluptatibus ipsam velit pariatur aut fuga, beatae reprehenderit itaque aperiam! Ipsam ipsa asperiores repellat dolor molestias? Et unde provident quos delectus vel, eos mollitia laboriosam necessitatibus dolor. Ea sit animi ullam, reprehenderit dignissimos veniam hic rem quaerat, quibusdam cupiditate incidunt nesciunt explicabo eos officiis velit accusantium commodi totam voluptatem dolorem cumque provident expedita. Natus cupiditate dignissimos, commodi, quidem facilis quod nulla vero quia similique sit quae. Praesentium culpa nisi dolorem, eaque asperiores magnam minima quibusdam consectetur perspiciatis temporibus fugiat soluta vero exercitationem necessitatibus atque nemo placeat laudantium. Quidem modi, nesciunt accusamus natus nihil, ipsum reiciendis id nisi eos quas, aperiam rerum inventore excepturi pariatur! Fugiat, cum vitae voluptates voluptatem, ullam atque velit consequatur aliquam iure quia similique soluta ipsum numquam minus autem dolores ut consequuntur!</div>
    </div>
  );
}
